# Generated by Django 5.2.4 on 2025-08-19 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='uploads/profile/default-avatar.png', null=True, upload_to='uploads/profile/'),
        ),
    ]
