# Generated by Django 5.2.4 on 2025-08-19 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_booking_borrower_alter_booking_tool'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_seen_by_borrower',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='is_seen_by_owner',
            field=models.BooleanField(default=False),
        ),
    ]
