# Generated by Django 5.2.4 on 2025-08-19 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_booking_is_seen_by_borrower_booking_is_seen_by_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='comment',
            field=models.TextField(blank=True, default=''),
        ),
    ]
